/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as CalendarEventIdRouteImport } from './routes/calendar/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarEventIdRoute = CalendarEventIdRouteImport.update({
  id: '/calendar/$eventId',
  path: '/calendar/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/calendar': typeof CalendarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/calendar': typeof CalendarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/calendar/': typeof CalendarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar/$eventId' | '/calendar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar/$eventId' | '/calendar'
  id: '__root__' | '/' | '/calendar/$eventId' | '/calendar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarEventIdRoute: typeof CalendarEventIdRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$eventId': {
      id: '/calendar/$eventId'
      path: '/calendar/$eventId'
      fullPath: '/calendar/$eventId'
      preLoaderRoute: typeof CalendarEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarEventIdRoute: CalendarEventIdRoute,
  CalendarIndexRoute: CalendarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
