import { RootRoute, Route } from '@tanstack/react-router'

import { createFileRoute } from '@tanstack/react-router'

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteRouteImport } from './routes/_sign-in/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SignInSignInRouteImport } from './routes/_sign-in/sign-in'
import { Route as AppUiIndexRouteImport } from './routes/_app/ui/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppUiTestFormsRouteImport } from './routes/_app/ui/test-forms'
import { Route as AppUiInputsRouteImport } from './routes/_app/ui/inputs'
import { Route as AppUiComboboxRouteImport } from './routes/_app/ui/combobox'
import { Route as AppUiButtonsRouteImport } from './routes/_app/ui/buttons'
import { Route as AppCalendarTemplatesRouteRouteImport } from './routes/_app/calendar/templates/route'
import { Route as AppAdminPositionsRouteRouteImport } from './routes/_app/admin/positions/route'
import { Route as AppCalendarTemplatesIndexRouteImport } from './routes/_app/calendar/templates/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminPositionsIndexRouteImport } from './routes/_app/admin/positions/index'
import { Route as AppAdminMatrixIndexRouteImport } from './routes/_app/admin/matrix/index'
import { Route as AppCalendarTemplatesNewRouteImport } from './routes/_app/calendar/templates/new'
import { Route as AppCalendarTemplatesTemplateIdRouteImport } from './routes/_app/calendar/templates/$templateId'
import { Route as AppCalendarEventsNewRouteImport } from './routes/_app/calendar/events.new'
import { Route as AppCalendarEventsEventIdRouteImport } from './routes/_app/calendar/events.$eventId'
import { Route as AppCalendarYearMonthRouteImport } from './routes/_app/calendar/$year.$month'
import { Route as AppAdminPositionsNewRouteImport } from './routes/_app/admin/positions/new'
import { Route as AppAdminPositionsPositionIdRouteImport } from './routes/_app/admin/positions/$positionId'
import { Route as AppAdminUsersUserIdRouteRouteImport } from './routes/_app/admin/users/$userId/route'
import { Route as AppAdminUsersUserIdIndexRouteImport } from './routes/_app/admin/users/$userId/index'
import { Route as AppAdminUsersUserIdProfileRouteImport } from './routes/_app/admin/users/$userId/profile'
import { Route as AppAdminUsersUserIdHistoryRouteImport } from './routes/_app/admin/users/$userId/history'

const SignInRouteRoute = SignInRouteRouteImport.update({
  id: '/_sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const SignInSignInRoute = SignInSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => SignInRouteRoute,
} as any)
const AppUiIndexRoute = AppUiIndexRouteImport.update({
  id: '/ui/',
  path: '/ui/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUiTestFormsRoute = AppUiTestFormsRouteImport.update({
  id: '/ui/test-forms',
  path: '/ui/test-forms',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUiInputsRoute = AppUiInputsRouteImport.update({
  id: '/ui/inputs',
  path: '/ui/inputs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUiComboboxRoute = AppUiComboboxRouteImport.update({
  id: '/ui/combobox',
  path: '/ui/combobox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUiButtonsRoute = AppUiButtonsRouteImport.update({
  id: '/ui/buttons',
  path: '/ui/buttons',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarTemplatesRouteRoute =
  AppCalendarTemplatesRouteRouteImport.update({
    id: '/calendar/templates',
    path: '/calendar/templates',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAdminPositionsRouteRoute = AppAdminPositionsRouteRouteImport.update({
  id: '/admin/positions',
  path: '/admin/positions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarTemplatesIndexRoute =
  AppCalendarTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCalendarTemplatesRouteRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminPositionsIndexRoute = AppAdminPositionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminPositionsRouteRoute,
} as any)
const AppAdminMatrixIndexRoute = AppAdminMatrixIndexRouteImport.update({
  id: '/admin/matrix/',
  path: '/admin/matrix/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarTemplatesNewRoute = AppCalendarTemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCalendarTemplatesRouteRoute,
} as any)
const AppCalendarTemplatesTemplateIdRoute =
  AppCalendarTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AppCalendarTemplatesRouteRoute,
  } as any)
const AppCalendarEventsNewRoute = AppCalendarEventsNewRouteImport.update({
  id: '/calendar/events/new',
  path: '/calendar/events/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarEventsEventIdRoute =
  AppCalendarEventsEventIdRouteImport.update({
    id: '/calendar/events/$eventId',
    path: '/calendar/events/$eventId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCalendarYearMonthRoute = AppCalendarYearMonthRouteImport.update({
  id: '/calendar/$year/$month',
  path: '/calendar/$year/$month',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminPositionsNewRoute = AppAdminPositionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAdminPositionsRouteRoute,
} as any)
const AppAdminPositionsPositionIdRoute =
  AppAdminPositionsPositionIdRouteImport.update({
    id: '/$positionId',
    path: '/$positionId',
    getParentRoute: () => AppAdminPositionsRouteRoute,
  } as any)
const AppAdminUsersUserIdRouteRoute =
  AppAdminUsersUserIdRouteRouteImport.update({
    id: '/admin/users/$userId',
    path: '/admin/users/$userId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAdminUsersUserIdIndexRoute =
  AppAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAdminUsersUserIdRouteRoute,
  } as any)
const AppAdminUsersUserIdProfileRoute =
  AppAdminUsersUserIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AppAdminUsersUserIdRouteRoute,
  } as any)
const AppAdminUsersUserIdHistoryRoute =
  AppAdminUsersUserIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AppAdminUsersUserIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInSignInRoute
  '/': typeof AppIndexRoute
  '/admin/positions': typeof AppAdminPositionsRouteRouteWithChildren
  '/calendar/templates': typeof AppCalendarTemplatesRouteRouteWithChildren
  '/ui/buttons': typeof AppUiButtonsRoute
  '/ui/combobox': typeof AppUiComboboxRoute
  '/ui/inputs': typeof AppUiInputsRoute
  '/ui/test-forms': typeof AppUiTestFormsRoute
  '/admin': typeof AppAdminIndexRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/ui': typeof AppUiIndexRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRouteRouteWithChildren
  '/admin/positions/$positionId': typeof AppAdminPositionsPositionIdRoute
  '/admin/positions/new': typeof AppAdminPositionsNewRoute
  '/calendar/$year/$month': typeof AppCalendarYearMonthRoute
  '/calendar/events/$eventId': typeof AppCalendarEventsEventIdRoute
  '/calendar/events/new': typeof AppCalendarEventsNewRoute
  '/calendar/templates/$templateId': typeof AppCalendarTemplatesTemplateIdRoute
  '/calendar/templates/new': typeof AppCalendarTemplatesNewRoute
  '/admin/matrix': typeof AppAdminMatrixIndexRoute
  '/admin/positions/': typeof AppAdminPositionsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/calendar/templates/': typeof AppCalendarTemplatesIndexRoute
  '/admin/users/$userId/history': typeof AppAdminUsersUserIdHistoryRoute
  '/admin/users/$userId/profile': typeof AppAdminUsersUserIdProfileRoute
  '/admin/users/$userId/': typeof AppAdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInSignInRoute
  '/': typeof AppIndexRoute
  '/ui/buttons': typeof AppUiButtonsRoute
  '/ui/combobox': typeof AppUiComboboxRoute
  '/ui/inputs': typeof AppUiInputsRoute
  '/ui/test-forms': typeof AppUiTestFormsRoute
  '/admin': typeof AppAdminIndexRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/ui': typeof AppUiIndexRoute
  '/admin/positions/$positionId': typeof AppAdminPositionsPositionIdRoute
  '/admin/positions/new': typeof AppAdminPositionsNewRoute
  '/calendar/$year/$month': typeof AppCalendarYearMonthRoute
  '/calendar/events/$eventId': typeof AppCalendarEventsEventIdRoute
  '/calendar/events/new': typeof AppCalendarEventsNewRoute
  '/calendar/templates/$templateId': typeof AppCalendarTemplatesTemplateIdRoute
  '/calendar/templates/new': typeof AppCalendarTemplatesNewRoute
  '/admin/matrix': typeof AppAdminMatrixIndexRoute
  '/admin/positions': typeof AppAdminPositionsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/calendar/templates': typeof AppCalendarTemplatesIndexRoute
  '/admin/users/$userId/history': typeof AppAdminUsersUserIdHistoryRoute
  '/admin/users/$userId/profile': typeof AppAdminUsersUserIdProfileRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_sign-in': typeof SignInRouteRouteWithChildren
  '/_sign-in/sign-in': typeof SignInSignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/positions': typeof AppAdminPositionsRouteRouteWithChildren
  '/_app/calendar/templates': typeof AppCalendarTemplatesRouteRouteWithChildren
  '/_app/ui/buttons': typeof AppUiButtonsRoute
  '/_app/ui/combobox': typeof AppUiComboboxRoute
  '/_app/ui/inputs': typeof AppUiInputsRoute
  '/_app/ui/test-forms': typeof AppUiTestFormsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/ui/': typeof AppUiIndexRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRouteRouteWithChildren
  '/_app/admin/positions/$positionId': typeof AppAdminPositionsPositionIdRoute
  '/_app/admin/positions/new': typeof AppAdminPositionsNewRoute
  '/_app/calendar/$year/$month': typeof AppCalendarYearMonthRoute
  '/_app/calendar/events/$eventId': typeof AppCalendarEventsEventIdRoute
  '/_app/calendar/events/new': typeof AppCalendarEventsNewRoute
  '/_app/calendar/templates/$templateId': typeof AppCalendarTemplatesTemplateIdRoute
  '/_app/calendar/templates/new': typeof AppCalendarTemplatesNewRoute
  '/_app/admin/matrix/': typeof AppAdminMatrixIndexRoute
  '/_app/admin/positions/': typeof AppAdminPositionsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/calendar/templates/': typeof AppCalendarTemplatesIndexRoute
  '/_app/admin/users/$userId/history': typeof AppAdminUsersUserIdHistoryRoute
  '/_app/admin/users/$userId/profile': typeof AppAdminUsersUserIdProfileRoute
  '/_app/admin/users/$userId/': typeof AppAdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/'
    | '/admin/positions'
    | '/calendar/templates'
    | '/ui/buttons'
    | '/ui/combobox'
    | '/ui/inputs'
    | '/ui/test-forms'
    | '/admin'
    | '/calendar'
    | '/ui'
    | '/admin/users/$userId'
    | '/admin/positions/$positionId'
    | '/admin/positions/new'
    | '/calendar/$year/$month'
    | '/calendar/events/$eventId'
    | '/calendar/events/new'
    | '/calendar/templates/$templateId'
    | '/calendar/templates/new'
    | '/admin/matrix'
    | '/admin/positions/'
    | '/admin/users'
    | '/calendar/templates/'
    | '/admin/users/$userId/history'
    | '/admin/users/$userId/profile'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/ui/buttons'
    | '/ui/combobox'
    | '/ui/inputs'
    | '/ui/test-forms'
    | '/admin'
    | '/calendar'
    | '/ui'
    | '/admin/positions/$positionId'
    | '/admin/positions/new'
    | '/calendar/$year/$month'
    | '/calendar/events/$eventId'
    | '/calendar/events/new'
    | '/calendar/templates/$templateId'
    | '/calendar/templates/new'
    | '/admin/matrix'
    | '/admin/positions'
    | '/admin/users'
    | '/calendar/templates'
    | '/admin/users/$userId/history'
    | '/admin/users/$userId/profile'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_app'
    | '/_sign-in'
    | '/_sign-in/sign-in'
    | '/_app/'
    | '/_app/admin/positions'
    | '/_app/calendar/templates'
    | '/_app/ui/buttons'
    | '/_app/ui/combobox'
    | '/_app/ui/inputs'
    | '/_app/ui/test-forms'
    | '/_app/admin/'
    | '/_app/calendar/'
    | '/_app/ui/'
    | '/_app/admin/users/$userId'
    | '/_app/admin/positions/$positionId'
    | '/_app/admin/positions/new'
    | '/_app/calendar/$year/$month'
    | '/_app/calendar/events/$eventId'
    | '/_app/calendar/events/new'
    | '/_app/calendar/templates/$templateId'
    | '/_app/calendar/templates/new'
    | '/_app/admin/matrix/'
    | '/_app/admin/positions/'
    | '/_app/admin/users/'
    | '/_app/calendar/templates/'
    | '/_app/admin/users/$userId/history'
    | '/_app/admin/users/$userId/profile'
    | '/_app/admin/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SignInRouteRoute: typeof SignInRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sign-in': {
      id: '/_sign-in'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_sign-in/sign-in': {
      id: '/_sign-in/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInSignInRouteImport
      parentRoute: typeof SignInRouteRoute
    }
    '/_app/ui/': {
      id: '/_app/ui/'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof AppUiIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ui/test-forms': {
      id: '/_app/ui/test-forms'
      path: '/ui/test-forms'
      fullPath: '/ui/test-forms'
      preLoaderRoute: typeof AppUiTestFormsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ui/inputs': {
      id: '/_app/ui/inputs'
      path: '/ui/inputs'
      fullPath: '/ui/inputs'
      preLoaderRoute: typeof AppUiInputsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ui/combobox': {
      id: '/_app/ui/combobox'
      path: '/ui/combobox'
      fullPath: '/ui/combobox'
      preLoaderRoute: typeof AppUiComboboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ui/buttons': {
      id: '/_app/ui/buttons'
      path: '/ui/buttons'
      fullPath: '/ui/buttons'
      preLoaderRoute: typeof AppUiButtonsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendar/templates': {
      id: '/_app/calendar/templates'
      path: '/calendar/templates'
      fullPath: '/calendar/templates'
      preLoaderRoute: typeof AppCalendarTemplatesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/positions': {
      id: '/_app/admin/positions'
      path: '/admin/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AppAdminPositionsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendar/templates/': {
      id: '/_app/calendar/templates/'
      path: '/'
      fullPath: '/calendar/templates/'
      preLoaderRoute: typeof AppCalendarTemplatesIndexRouteImport
      parentRoute: typeof AppCalendarTemplatesRouteRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/positions/': {
      id: '/_app/admin/positions/'
      path: '/'
      fullPath: '/admin/positions/'
      preLoaderRoute: typeof AppAdminPositionsIndexRouteImport
      parentRoute: typeof AppAdminPositionsRouteRoute
    }
    '/_app/admin/matrix/': {
      id: '/_app/admin/matrix/'
      path: '/admin/matrix'
      fullPath: '/admin/matrix'
      preLoaderRoute: typeof AppAdminMatrixIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendar/templates/new': {
      id: '/_app/calendar/templates/new'
      path: '/new'
      fullPath: '/calendar/templates/new'
      preLoaderRoute: typeof AppCalendarTemplatesNewRouteImport
      parentRoute: typeof AppCalendarTemplatesRouteRoute
    }
    '/_app/calendar/templates/$templateId': {
      id: '/_app/calendar/templates/$templateId'
      path: '/$templateId'
      fullPath: '/calendar/templates/$templateId'
      preLoaderRoute: typeof AppCalendarTemplatesTemplateIdRouteImport
      parentRoute: typeof AppCalendarTemplatesRouteRoute
    }
    '/_app/calendar/events/new': {
      id: '/_app/calendar/events/new'
      path: '/calendar/events/new'
      fullPath: '/calendar/events/new'
      preLoaderRoute: typeof AppCalendarEventsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendar/events/$eventId': {
      id: '/_app/calendar/events/$eventId'
      path: '/calendar/events/$eventId'
      fullPath: '/calendar/events/$eventId'
      preLoaderRoute: typeof AppCalendarEventsEventIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendar/$year/$month': {
      id: '/_app/calendar/$year/$month'
      path: '/calendar/$year/$month'
      fullPath: '/calendar/$year/$month'
      preLoaderRoute: typeof AppCalendarYearMonthRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/positions/new': {
      id: '/_app/admin/positions/new'
      path: '/new'
      fullPath: '/admin/positions/new'
      preLoaderRoute: typeof AppAdminPositionsNewRouteImport
      parentRoute: typeof AppAdminPositionsRouteRoute
    }
    '/_app/admin/positions/$positionId': {
      id: '/_app/admin/positions/$positionId'
      path: '/$positionId'
      fullPath: '/admin/positions/$positionId'
      preLoaderRoute: typeof AppAdminPositionsPositionIdRouteImport
      parentRoute: typeof AppAdminPositionsRouteRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users/$userId/': {
      id: '/_app/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AppAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AppAdminUsersUserIdRouteRoute
    }
    '/_app/admin/users/$userId/profile': {
      id: '/_app/admin/users/$userId/profile'
      path: '/profile'
      fullPath: '/admin/users/$userId/profile'
      preLoaderRoute: typeof AppAdminUsersUserIdProfileRouteImport
      parentRoute: typeof AppAdminUsersUserIdRouteRoute
    }
    '/_app/admin/users/$userId/history': {
      id: '/_app/admin/users/$userId/history'
      path: '/history'
      fullPath: '/admin/users/$userId/history'
      preLoaderRoute: typeof AppAdminUsersUserIdHistoryRouteImport
      parentRoute: typeof AppAdminUsersUserIdRouteRoute
    }
  }
}

interface AppAdminPositionsRouteRouteChildren {
  AppAdminPositionsPositionIdRoute: typeof AppAdminPositionsPositionIdRoute
  AppAdminPositionsNewRoute: typeof AppAdminPositionsNewRoute
  AppAdminPositionsIndexRoute: typeof AppAdminPositionsIndexRoute
}

const AppAdminPositionsRouteRouteChildren: AppAdminPositionsRouteRouteChildren =
  {
    AppAdminPositionsPositionIdRoute: AppAdminPositionsPositionIdRoute,
    AppAdminPositionsNewRoute: AppAdminPositionsNewRoute,
    AppAdminPositionsIndexRoute: AppAdminPositionsIndexRoute,
  }

const AppAdminPositionsRouteRouteWithChildren =
  AppAdminPositionsRouteRoute._addFileChildren(
    AppAdminPositionsRouteRouteChildren,
  )

interface AppCalendarTemplatesRouteRouteChildren {
  AppCalendarTemplatesTemplateIdRoute: typeof AppCalendarTemplatesTemplateIdRoute
  AppCalendarTemplatesNewRoute: typeof AppCalendarTemplatesNewRoute
  AppCalendarTemplatesIndexRoute: typeof AppCalendarTemplatesIndexRoute
}

const AppCalendarTemplatesRouteRouteChildren: AppCalendarTemplatesRouteRouteChildren =
  {
    AppCalendarTemplatesTemplateIdRoute: AppCalendarTemplatesTemplateIdRoute,
    AppCalendarTemplatesNewRoute: AppCalendarTemplatesNewRoute,
    AppCalendarTemplatesIndexRoute: AppCalendarTemplatesIndexRoute,
  }

const AppCalendarTemplatesRouteRouteWithChildren =
  AppCalendarTemplatesRouteRoute._addFileChildren(
    AppCalendarTemplatesRouteRouteChildren,
  )

interface AppAdminUsersUserIdRouteRouteChildren {
  AppAdminUsersUserIdHistoryRoute: typeof AppAdminUsersUserIdHistoryRoute
  AppAdminUsersUserIdProfileRoute: typeof AppAdminUsersUserIdProfileRoute
  AppAdminUsersUserIdIndexRoute: typeof AppAdminUsersUserIdIndexRoute
}

const AppAdminUsersUserIdRouteRouteChildren: AppAdminUsersUserIdRouteRouteChildren =
  {
    AppAdminUsersUserIdHistoryRoute: AppAdminUsersUserIdHistoryRoute,
    AppAdminUsersUserIdProfileRoute: AppAdminUsersUserIdProfileRoute,
    AppAdminUsersUserIdIndexRoute: AppAdminUsersUserIdIndexRoute,
  }

const AppAdminUsersUserIdRouteRouteWithChildren =
  AppAdminUsersUserIdRouteRoute._addFileChildren(
    AppAdminUsersUserIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminPositionsRouteRoute: typeof AppAdminPositionsRouteRouteWithChildren
  AppCalendarTemplatesRouteRoute: typeof AppCalendarTemplatesRouteRouteWithChildren
  AppUiButtonsRoute: typeof AppUiButtonsRoute
  AppUiComboboxRoute: typeof AppUiComboboxRoute
  AppUiInputsRoute: typeof AppUiInputsRoute
  AppUiTestFormsRoute: typeof AppUiTestFormsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppUiIndexRoute: typeof AppUiIndexRoute
  AppAdminUsersUserIdRouteRoute: typeof AppAdminUsersUserIdRouteRouteWithChildren
  AppCalendarYearMonthRoute: typeof AppCalendarYearMonthRoute
  AppCalendarEventsEventIdRoute: typeof AppCalendarEventsEventIdRoute
  AppCalendarEventsNewRoute: typeof AppCalendarEventsNewRoute
  AppAdminMatrixIndexRoute: typeof AppAdminMatrixIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminPositionsRouteRoute: AppAdminPositionsRouteRouteWithChildren,
  AppCalendarTemplatesRouteRoute: AppCalendarTemplatesRouteRouteWithChildren,
  AppUiButtonsRoute: AppUiButtonsRoute,
  AppUiComboboxRoute: AppUiComboboxRoute,
  AppUiInputsRoute: AppUiInputsRoute,
  AppUiTestFormsRoute: AppUiTestFormsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppUiIndexRoute: AppUiIndexRoute,
  AppAdminUsersUserIdRouteRoute: AppAdminUsersUserIdRouteRouteWithChildren,
  AppCalendarYearMonthRoute: AppCalendarYearMonthRoute,
  AppCalendarEventsEventIdRoute: AppCalendarEventsEventIdRoute,
  AppCalendarEventsNewRoute: AppCalendarEventsNewRoute,
  AppAdminMatrixIndexRoute: AppAdminMatrixIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SignInRouteRouteChildren {
  SignInSignInRoute: typeof SignInSignInRoute
}

const SignInRouteRouteChildren: SignInRouteRouteChildren = {
  SignInSignInRoute: SignInSignInRoute,
}

const SignInRouteRouteWithChildren = SignInRouteRoute._addFileChildren(
  SignInRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  SignInRouteRoute: SignInRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
